### ISSUE TITLE
M2_OOB : Support @Redfish.Settings object in Redfish PATCH

### ISSUE THREAD

**Issue by gtossk2** [ARM-software/sbmr-acs#3] opened 2023-11-10 13:44 UTC
Some BMC might has @Redfish.Settings object in Redfish URIs. Test case need to check @Redfish.Settings object before patching a resource.

Reference : 
-   https://redfish.dmtf.org/schemas/v1/Settings.v1_1_6.json
-   https://www.dmtf.org/sites/default/files/standards/documents/DSP2046_2019.2.pdf

**Comment by amrathesh** [comment] 2024-01-10 04:40
Hi @gtossk2, 

We have modified the patch function to check for @Redfish.Settings object in Redfish URIs being patched and use the URI present in SettingObject to patch the resource. 

Please provide your review for PR #9

Regards,
ACS Team

**Comment by edhay** [comment] 2024-01-10 04:44
The PR is reviewed and approved

**Comment by amrathesh** [comment] 2024-01-10 04:54
Hi @gtossk2, 

The solution for the issue is merged with commit https://github.com/ARM-software/sbmr-acs/commit/0036d1492fa6ea0b470a4e32a578e9d6fcf05432 , To test out the solution, one can download the zipped repo artifact from https://github.com/ARM-software/sbmr-acs/actions/runs/7470437269.

Regards,
ACS Team

**Closed by amrathesh** 2024-01-10 04:54 UTC
